# Generated by Django 5.0.1 on 2024-03-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapps', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='Mobile is a new Technology', max_length=100),
        ),
    ]
