# Generated by Django 5.0.1 on 2024-03-06 09:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapps', '0003_product_model_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
